networks:
    1panel-network:
        external: true
services:
  musicon-go:
    image: icezxf/musicon:aa
    container_name: musicon-go
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - "8002:8000"
    environment:
      LISTEN: "0.0.0.0:8000"
      DB_PATH: "/app/data/musicon.db"
      WEB_USER: "fire"
      WEB_PASS: "boc81838"
    volumes:
      - ./data:/app/data
